# Generated by Django 5.2 on 2025-04-24 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_cart_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='items',
        ),
    ]
